
name: Update README

on:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

env:

  CREDLY_USER: mahdtech

jobs:

  build:

    name: Update README with recent GitHub activity

    runs-on: ubuntu-latest

    steps:

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      # NOTE: Only these public events will show up
      #         - IssueEvent
      #         - IssueCommentEvent
      #         - PullRequestEvent
      - id: update_readme
        name: Update Readme
        uses: Readme-Workflows/recent-activity@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: update_badges
        name: Update Badges
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COMMIT_MESSAGE: "Update Credly Badges"
          CREDLY_USER: "${{ env.CREDLY_USER }}"
          CREDLY_SORT: RECENT

