
name: Update README

on:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  build:

    name: Update README with recent GitHub activity

    runs-on: ubuntu-latest

    steps:

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      # NOTE: Only these public events will show up
      #         - IssueEvent
      #         - IssueCommentEvent
      #         - PullRequestEvent
      - id: update_readme
        name: Update Readme
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update README with recent GitHub activity"
          MAX_LINES: 10

